### ISSUE TITLE
"Waiting time"

### ISSUE THREAD

**Issue by LnobAnne** [OHFLesvos/free-shop#24]
Hello,

There is a problem with the "waiting time". One time a visitor came to the Free Shop, the system told him that he is allwoded to take items in 1h. After 1h10min the man came again and the system said that he had to wait 34min. I wonder why is that and I hope there is a possibility to fix it. If there are any questions please write me an Email (a.kessling@lnob.net). Thank you for your help

**Comment by mrcage** [comment]
Fixed in f6a8c98b8048fc856c284c54636528d758d4be98

The next order date calculation is now based on full days (i.e. counting from midnight), and the date shown to the user will be displayed as a full date, instead of a duration (in xx days/hours/...) from now

**Comment by mrcage** [comment]
I have updated the software on the live/production instance of the free shop server

**Comment by LnobAnne** [comment]
Thank you! Have a nice day 


Am Sonntag, April 02, 2023 20:46 EEST, schrieb Nicolas Perrenoud ***@***.***>:
 
 
I have updated the software on the live/production instance of the free shop server
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/OHFLesvos/free-shop/issues/24#issuecomment-1493400809", "url": "https://github.com/OHFLesvos/free-shop/issues/24#issuecomment-1493400809", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]***>


-- 
Anne Kessling
Coordinator of Operations Lesbos
LeaveNoOneBehind

***@***.***
Phone: +49 176 39 22 50 02
            +30 698 894 1423
 
Website: https://lnob.net/
